#!/bin/bash

if [ $0 == "$BASH_SOURCE" ]
then
        echo "Please run this script with source. Exiting."
        exit 1
fi

source /usr/local/bin/virtualenvwrapper.sh
workon serium 2>/dev/null


if [ "x$VIRTUAL_ENV" == "x" ];
then
        echo "Could not go into virtual env. exiting. Make sure that you've run ./dev/prepare-dev-machine so that the virtualenv exists"
else
        echo "Activating serium virtual env"
        pip install -r ./requirements.txt

        ./setup.py develop
fi
